export interface ToolMeta {
  id: string;
  name: string;
  route: string;
  category: 'json' | 'yaml' | 'xml' | 'markup' | 'security' | 'encoding' | 'utility';
  description: string;
  shortDescription: string;
  icon: string;
  keywords: string[];
  sampleInput: string;
  sampleOutput: string;
  faq: { q: string; a: string }[];
  relatedTools: string[];
  seoH1: string;
  seoExtra: {
    comparisonTitle: string;
    comparisonRows: { label: string; left: string; right: string }[];
    commonErrors: string[];
    useCases: string[];
    longDescription: string;
  };
}

export const TOOLS: ToolMeta[] = [
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    route: '/json-formatter',
    category: 'json',
    description:
      'Format and beautify your JSON data with proper indentation. Paste raw JSON and get a clean, readable output instantly.',
    shortDescription: 'Beautify JSON with proper indentation',
    icon: '{ }',
    keywords: ['json', 'formatter', 'beautify', 'prettify', 'indent', 'pretty print'],
    sampleInput: '{"name":"John Doe","age":30,"address":{"street":"123 Main St","city":"Springfield"},"hobbies":["reading","gaming","cooking"]}',
    sampleOutput: '{\n  "name": "John Doe",\n  "age": 30,\n  "address": {\n    "street": "123 Main St",\n    "city": "Springfield"\n  },\n  "hobbies": [\n    "reading",\n    "gaming",\n    "cooking"\n  ]\n}',
    seoH1: 'JSON Formatter — Beautify & Pretty Print JSON Online Free',
    seoExtra: {
      comparisonTitle: 'Formatted vs Minified JSON',
      comparisonRows: [
        { label: 'Readability', left: 'Easy to read and debug', right: 'Hard to read' },
        { label: 'File Size', left: 'Larger due to whitespace', right: 'Smallest possible' },
        { label: 'Use Case', left: 'Development, debugging, code review', right: 'Production, APIs, storage' },
        { label: 'Indentation', left: '2 or 4 spaces per level', right: 'No indentation' },
        { label: 'Line Breaks', left: 'One property per line', right: 'Single line' },
      ],
      commonErrors: [
        'Trailing commas after the last property in an object or array are not valid JSON',
        'Single quotes around strings — JSON requires double quotes',
        'Unquoted property keys — all JSON keys must be wrapped in double quotes',
        'Missing commas between properties or array elements',
        'Comments (// or /* */) are not allowed in standard JSON',
      ],
      useCases: [
        'Debugging API responses by making minified JSON readable',
        'Preparing JSON configuration files for code review',
        'Formatting database exports for analysis',
        'Making JSON payloads readable in documentation',
        'Cleaning up JSON output from command-line tools',
      ],
      longDescription: 'JSON (JavaScript Object Notation) is the most widely used data interchange format on the web. When JSON is transmitted over networks or stored in databases, it is often minified to save bandwidth. Our JSON Formatter tool takes compressed or unformatted JSON and transforms it into a clean, indented structure with 2-space indentation, proper line breaks, and consistent formatting. This makes it easy to visually inspect nested objects, debug API responses, and prepare configuration files for version control. The formatter handles all valid JSON types including strings, numbers, booleans, null values, arrays, and deeply nested objects. Processing happens entirely in your browser using the native JSON.parse and JSON.stringify APIs, so your data remains private and never touches any server.',
    },
    faq: [
      {
        q: 'What is JSON Formatter?',
        a: 'JSON Formatter is a free online tool that takes raw or minified JSON data and formats it with proper indentation and line breaks, making it easy to read and debug.',
      },
      {
        q: 'How do I format JSON online?',
        a: 'Paste your JSON into the editor on the left panel and press Ctrl+Enter or click the Run button. The formatted output with proper indentation appears instantly in the right panel.',
      },
      {
        q: 'Is my JSON data safe when using this tool?',
        a: 'Yes. All processing happens entirely in your browser using JavaScript. No data is ever sent to any server. You can verify this by checking the Network tab in your browser DevTools.',
      },
      {
        q: 'What indentation does the JSON formatter use?',
        a: 'The formatter uses 2-space indentation by default. Each nested level of objects and arrays is indented by 2 additional spaces for clear visual hierarchy.',
      },
      {
        q: 'Can I format invalid JSON?',
        a: 'No. The formatter requires valid JSON as input. If your JSON has syntax errors like trailing commas, unquoted keys, or single quotes, you will see an error message. Use our JSON Validator to identify the exact errors first.',
      },
    ],
    relatedTools: ['json-validator', 'json-minifier', 'json-to-xml'],
  },
  {
    id: 'json-validator',
    name: 'JSON Validator',
    route: '/json-validator',
    category: 'json',
    description:
      'Validate your JSON data and get detailed error messages with line numbers. Instantly find syntax errors in any JSON string.',
    shortDescription: 'Validate JSON and find syntax errors',
    icon: '✓',
    keywords: ['json', 'validator', 'lint', 'check', 'syntax', 'verify'],
    sampleInput: '{"name": "Test", "items": [1, 2, 3], "valid": true}',
    sampleOutput: '✓ Valid JSON',
    seoH1: 'JSON Validator — Check & Validate JSON Syntax Online Free',
    seoExtra: {
      comparisonTitle: 'JSON Validator vs JSON Formatter',
      comparisonRows: [
        { label: 'Purpose', left: 'Checks if JSON is syntactically correct', right: 'Reformats valid JSON with indentation' },
        { label: 'Output', left: 'Valid/Invalid status with error details', right: 'Reformatted JSON string' },
        { label: 'Modifies Input', left: 'No — read-only check', right: 'Yes — reformats whitespace' },
        { label: 'Error Reporting', left: 'Detailed error messages with position', right: 'Only shows parsing errors' },
        { label: 'Best For', left: 'Debugging broken JSON', right: 'Making valid JSON readable' },
      ],
      commonErrors: [
        'Trailing comma after the last element — remove the comma before the closing bracket',
        'Single quotes instead of double quotes — JSON strictly requires double quotes for strings and keys',
        'Missing closing brackets — every { must have a matching } and every [ must have a matching ]',
        'Undefined or NaN values — these are not valid JSON; use null instead',
        'Unescaped special characters in strings — backslashes, newlines, and tabs must be escaped',
      ],
      useCases: [
        'Debugging API response errors before processing in your application',
        'Validating JSON configuration files before deployment',
        'Checking JSON payloads before sending POST/PUT requests',
        'Verifying JSON data exported from databases or spreadsheets',
        'Testing JSON output from code generators and templating systems',
      ],
      longDescription: 'JSON validation is a critical step in any development workflow that involves data interchange. Even a single misplaced comma, missing bracket, or unquoted key can cause an entire API request to fail or a configuration file to be rejected. Our JSON Validator parses your input using the browser\'s native JSON.parse engine and reports the exact error type and character position when validation fails. Unlike basic syntax checkers, this tool provides human-readable error messages that help you pinpoint problems quickly. For valid JSON, you get a clear confirmation message. The validator handles all JSON data types and structures including deeply nested objects, large arrays, Unicode characters, and escaped sequences. Because all validation happens in your browser, there is zero latency and your sensitive data never leaves your machine.',
    },
    faq: [
      {
        q: 'What is JSON Validator?',
        a: 'JSON Validator is a free online tool that checks whether your JSON string is syntactically correct. It highlights exact error positions with detailed messages to help you fix issues quickly.',
      },
      {
        q: 'What types of errors can it detect?',
        a: 'It detects all JSON syntax errors including missing brackets, trailing commas, unquoted keys, invalid escape sequences, duplicate keys, and improperly nested structures.',
      },
      {
        q: 'Does JSON Validator modify my data?',
        a: 'No. The validator is read-only — it only checks your JSON for errors and never changes your input data. If you want to reformat your JSON, use the JSON Formatter.',
      },
      {
        q: 'What is the difference between JSON Validator and JSON Lint?',
        a: 'JSON Lint is another name for JSON validation. Our JSON Validator performs the same function as JSONLint — it parses your JSON and reports syntax errors. Both terms refer to checking JSON for correctness.',
      },
      {
        q: 'Can I validate very large JSON files?',
        a: 'Yes. Since validation runs in your browser, it can handle large JSON files limited only by your browser\'s memory. For files over 10MB, processing may take a few seconds.',
      },
    ],
    relatedTools: ['json-formatter', 'json-minifier', 'json-to-xml'],
  },
  {
    id: 'json-minifier',
    name: 'JSON Minifier',
    route: '/json-minifier',
    category: 'json',
    description:
      'Minify JSON by removing all whitespace and line breaks. Reduce file size for storage, APIs, and network transmission.',
    shortDescription: 'Minify JSON to reduce size',
    icon: '⊟',
    keywords: ['json', 'minifier', 'compress', 'compact', 'minimize', 'uglify'],
    sampleInput: '{\n  "name": "John Doe",\n  "age": 30,\n  "address": {\n    "street": "123 Main St",\n    "city": "Springfield"\n  }\n}',
    sampleOutput: '{"name":"John Doe","age":30,"address":{"street":"123 Main St","city":"Springfield"}}',
    seoH1: 'JSON Minifier — Compress & Minify JSON Online Free',
    seoExtra: {
      comparisonTitle: 'Minified vs Formatted JSON',
      comparisonRows: [
        { label: 'File Size', left: 'Smallest possible', right: 'Larger due to whitespace' },
        { label: 'Readability', left: 'Not human-readable', right: 'Easy to read' },
        { label: 'Use Case', left: 'APIs, storage, production', right: 'Development, debugging' },
        { label: 'Bandwidth', left: 'Reduces network transfer', right: 'Uses more bandwidth' },
        { label: 'Performance', left: 'Faster parsing (fewer characters)', right: 'Slightly slower parsing' },
      ],
      commonErrors: [
        'Input must be valid JSON — minification fails if the JSON has syntax errors',
        'Minification does not remove data — it only strips whitespace characters',
        'Unicode characters are preserved exactly as they appear in the original',
        'Numeric precision is maintained — no rounding or truncation occurs',
        'Empty objects {} and empty arrays [] remain unchanged after minification',
      ],
      useCases: [
        'Reducing JSON payload size before sending API requests',
        'Compressing JSON configuration files for production deployment',
        'Minimizing localStorage usage in web applications',
        'Preparing JSON data for embedding in HTML or JavaScript',
        'Reducing bandwidth costs for JSON-heavy API endpoints',
      ],
      longDescription: 'JSON minification is the process of removing all unnecessary whitespace, line breaks, and indentation from a JSON string while preserving its data integrity. This produces the most compact valid JSON representation, which is critical for reducing bandwidth usage in API responses, minimizing storage costs in databases, and improving parse performance in client-side applications. Our JSON Minifier processes your data entirely in the browser — it parses the JSON into a JavaScript object and re-serializes it without any formatting. The output is guaranteed to be valid JSON with identical data to the original. Typical size reductions range from 20% to 60% depending on the original formatting. For production APIs that serve millions of requests, even small per-response savings add up to significant bandwidth and cost reductions.',
    },
    faq: [
      {
        q: 'What is JSON Minifier?',
        a: 'JSON Minifier is a free tool that compresses JSON by stripping all unnecessary whitespace, line breaks, and indentation to produce the smallest valid JSON string possible.',
      },
      {
        q: 'Why should I minify JSON?',
        a: 'Minified JSON uses less bandwidth and storage. It is ideal for API responses, configuration payloads, embedding in scripts, and any scenario where file size matters.',
      },
      {
        q: 'Does minification change my data?',
        a: 'No. Only whitespace characters are removed. All data values, structure, key names, and nesting remain identical. You can always re-format minified JSON back to readable form.',
      },
      {
        q: 'How much smaller does JSON get after minification?',
        a: 'Typical size reductions range from 20% to 60%, depending on how much indentation and formatting the original JSON contained. Deeply nested JSON with large indentation sees the biggest reductions.',
      },
      {
        q: 'Is JSON Minifier the same as JSON Compressor?',
        a: 'JSON minification and compression are often used interchangeably, but technically minification removes whitespace while compression (like gzip) uses algorithms to further reduce size. This tool performs minification.',
      },
    ],
    relatedTools: ['json-formatter', 'json-validator', 'json-to-xml'],
  },
  {
    id: 'json-to-xml',
    name: 'JSON to XML',
    route: '/json-to-xml',
    category: 'json',
    description:
      'Convert JSON data to well-formed XML. Supports nested objects, arrays, and all JSON value types with proper indentation.',
    shortDescription: 'Convert JSON to XML format',
    icon: '⇄',
    keywords: ['json', 'xml', 'convert', 'transform', 'export', 'converter'],
    sampleInput: '{"bookstore":{"book":[{"title":"The Great Gatsby","author":"F. Scott Fitzgerald","year":1925},{"title":"1984","author":"George Orwell","year":1949}]}}',
    sampleOutput: '<?xml version="1.0" encoding="UTF-8"?>\n<root>\n  <bookstore>\n    <book>\n      <item_0>\n        <title>The Great Gatsby</title>\n        <author>F. Scott Fitzgerald</author>\n        <year>1925</year>\n      </item_0>\n    </book>\n  </bookstore>\n</root>',
    seoH1: 'JSON to XML Converter — Convert JSON to XML Online Free',
    seoExtra: {
      comparisonTitle: 'JSON vs XML Comparison',
      comparisonRows: [
        { label: 'Syntax', left: 'Key-value pairs, arrays', right: 'Tags with attributes' },
        { label: 'Readability', left: 'More compact', right: 'More verbose' },
        { label: 'Data Types', left: 'String, number, boolean, null, array, object', right: 'All text (needs schema for types)' },
        { label: 'File Size', left: 'Smaller', right: 'Larger due to closing tags' },
        { label: 'Parsing', left: 'Native in JavaScript', right: 'Requires XML parser' },
        { label: 'Comments', left: 'Not supported', right: 'Supported' },
      ],
      commonErrors: [
        'Invalid JSON input — make sure your JSON is valid before converting',
        'Keys with special characters get sanitized (spaces become underscores)',
        'Arrays produce <item_0>, <item_1> elements — not repeated same-name tags',
        'Null values produce self-closing tags like <field />',
        'Root element is always <root> — rename after export if needed',
      ],
      useCases: [
        'Migrating data from JSON-based APIs to XML-based legacy systems',
        'Generating XML feeds from JSON data sources',
        'Converting JSON configuration to XML format for Java/.NET applications',
        'Creating SOAP payloads from RESTful JSON responses',
        'Exporting data for systems that only accept XML input',
      ],
      longDescription: 'JSON and XML are the two most common data interchange formats used in software development. While JSON dominates modern web APIs due to its compact syntax and native JavaScript support, many enterprise systems, SOAP web services, and legacy applications still require XML. Our JSON to XML converter bridges this gap by transforming any valid JSON structure into well-formed, properly indented XML. The conversion handles all JSON types: strings become text content, numbers and booleans become text nodes, null values produce self-closing tags, arrays are wrapped with indexed child elements, and nested objects create hierarchical XML elements. Special characters in keys are automatically sanitized to produce valid XML element names. The output includes an XML declaration header and uses 2-space indentation for readability.',
    },
    faq: [
      {
        q: 'How does JSON to XML conversion work?',
        a: 'Each JSON key becomes an XML element name. String, number, and boolean values become text content. Arrays are wrapped in a parent element with numbered child items (item_0, item_1). Null values produce self-closing tags.',
      },
      {
        q: 'Does it handle deeply nested JSON?',
        a: 'Yes. The converter recursively processes all levels of nesting. Deeply nested objects and arrays are converted into properly indented, hierarchical XML elements.',
      },
      {
        q: 'Can I convert XML back to JSON?',
        a: 'This tool currently only converts JSON to XML. An XML to JSON converter is planned for a future release. You can use other tools in the meantime for the reverse conversion.',
      },
      {
        q: 'What happens to special characters in JSON keys?',
        a: 'JSON keys containing spaces, dots, or other special characters are automatically sanitized. Non-alphanumeric characters (except hyphens and underscores) are replaced with underscores to produce valid XML element names.',
      },
      {
        q: 'Is the output valid XML?',
        a: 'Yes. The output includes a proper XML declaration (<?xml version="1.0" encoding="UTF-8"?>) and all elements are properly nested and closed. Special characters in values are escaped using XML entities (&amp; &lt; &gt;).',
      },
    ],
    relatedTools: ['xml-to-json', 'json-formatter', 'json-validator'],
  },
  {
    id: 'base64',
    name: 'Base64 Encode/Decode',
    route: '/base64',
    category: 'encoding',
    description:
      'Encode text to Base64 or decode Base64 strings back to plain text. Supports full UTF-8 encoding for multi-byte characters.',
    shortDescription: 'Encode and decode Base64 strings',
    icon: 'B64',
    keywords: ['base64', 'encode', 'decode', 'binary', 'text', 'encoder', 'decoder'],
    sampleInput: 'Hello, World! This is a test string for Base64 encoding.',
    sampleOutput: 'SGVsbG8sIFdvcmxkISBUaGlzIGlzIGEgdGVzdCBzdHJpbmcgZm9yIEJhc2U2NCBlbmNvZGluZy4=',
    seoH1: 'Base64 Encoder & Decoder — Encode and Decode Base64 Online Free',
    seoExtra: {
      comparisonTitle: 'Base64 vs Plain Text',
      comparisonRows: [
        { label: 'Characters Used', left: 'A-Z, a-z, 0-9, +, /, = (64 chars)', right: 'Full ASCII/Unicode range' },
        { label: 'Size', left: '~33% larger than original', right: 'Original size' },
        { label: 'Binary Safe', left: 'Yes — any binary data can be encoded', right: 'No — binary data may be corrupted' },
        { label: 'Transport Safe', left: 'Safe for email, URLs, JSON', right: 'May break in certain transports' },
        { label: 'Encryption', left: 'No — Base64 is encoding, not encryption', right: 'N/A' },
      ],
      commonErrors: [
        'Base64 is encoding, not encryption — do not use it to protect sensitive data',
        'Invalid Base64 strings cause decode errors — ensure the input has valid characters and correct padding',
        'Line breaks in Base64 strings may cause issues — remove them before decoding',
        'Non-ASCII characters require UTF-8 encoding before Base64 encoding',
        'Missing padding characters (=) at the end may produce incorrect decode results',
      ],
      useCases: [
        'Encoding images or files for embedding in HTML data URIs',
        'Encoding binary attachments for email (MIME) transport',
        'Creating Base64-encoded API authentication tokens',
        'Encoding data for safe inclusion in JSON strings',
        'Debugging encoded values in JWT tokens, cookies, and API headers',
      ],
      longDescription: 'Base64 is a binary-to-text encoding scheme that converts binary data into a string of printable ASCII characters. It uses a 64-character alphabet (A-Z, a-z, 0-9, +, /) plus = for padding. Base64 encoding is essential in web development for embedding binary data in text-based formats like HTML, CSS, JSON, and email. Common use cases include data URIs for inline images, MIME encoding for email attachments, encoding binary API payloads, and debugging JWT tokens. Our encoder handles full UTF-8 text by first converting multi-byte characters to their byte representation before encoding. The decoder reverses this process, properly handling UTF-8 byte sequences. Base64 encoding increases data size by approximately 33%, which is the trade-off for transport safety. Remember that Base64 is not encryption — it is a reversible encoding scheme that provides no security.',
    },
    faq: [
      {
        q: 'What is Base64 encoding?',
        a: 'Base64 is a binary-to-text encoding scheme that represents binary data as printable ASCII characters using a 64-character alphabet. It is commonly used in emails, data URIs, API tokens, and JWT.',
      },
      {
        q: 'How do I switch between encode and decode mode?',
        a: 'Use the mode toggle (Encode/Decode) above the editor. In Encode mode, your input is plain text and the output is Base64. In Decode mode, the input is Base64 and the output is plain text.',
      },
      {
        q: 'Does this tool support UTF-8 characters?',
        a: 'Yes. The tool uses the TextEncoder and TextDecoder APIs to properly handle multi-byte UTF-8 characters including emojis, Chinese characters, Arabic text, and other Unicode content.',
      },
      {
        q: 'Is Base64 the same as encryption?',
        a: 'No. Base64 is encoding, not encryption. Anyone can decode a Base64 string without any key. Never use Base64 to protect sensitive data — use proper encryption algorithms like AES instead.',
      },
      {
        q: 'Why does Base64 make the data larger?',
        a: 'Base64 encoding represents every 3 bytes of input as 4 ASCII characters, resulting in approximately 33% size increase. This is the trade-off for making binary data safe to transmit through text-based protocols.',
      },
    ],
    relatedTools: ['json-formatter', 'json-minifier', 'json-validator'],
  },
  // ─── JSON Cluster (promoted / new) ─────────────────────────────
  {
    id: 'json-to-csv',
    name: 'JSON to CSV',
    route: '/json-to-csv',
    category: 'json',
    description: 'Convert JSON array or object to CSV format. Supports nested objects and arrays.',
    shortDescription: 'Convert JSON to CSV',
    icon: '⇄',
    keywords: ['json', 'csv', 'convert', 'export', 'converter'],
    sampleInput: '[{"name":"John","age":30},{"name":"Jane","age":25}]',
    sampleOutput: 'name,age\nJohn,30\nJane,25',
    seoH1: 'JSON to CSV Converter — Convert JSON to CSV Online Free',
    seoExtra: {
      comparisonTitle: 'JSON vs CSV',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Export JSON API data to spreadsheet format', 'Convert database exports to CSV'],
      longDescription: 'Convert JSON data to CSV format for use in spreadsheets and data analysis tools.',
    },
    faq: [
      { q: 'How does JSON to CSV work?', a: 'The first object or array element defines the headers. Each subsequent object maps to a row with values for each header.' },
    ],
    relatedTools: ['csv-to-json', 'json-formatter', 'json-to-yaml'],
  },
  {
    id: 'json-to-yaml',
    name: 'JSON to YAML',
    route: '/json-to-yaml',
    category: 'json',
    description: 'Convert JSON to YAML format. Preserves structure with readable indentation.',
    shortDescription: 'Convert JSON to YAML',
    icon: '⇄',
    keywords: ['json', 'yaml', 'convert', 'export', 'converter'],
    sampleInput: '{"name":"John","age":30}',
    sampleOutput: 'name: John\nage: 30',
    seoH1: 'JSON to YAML Converter — Convert JSON to YAML Online Free',
    seoExtra: {
      comparisonTitle: 'JSON vs YAML',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Convert API responses to config files', 'Migrate JSON configs to YAML'],
      longDescription: 'Convert JSON data to YAML for configuration files and readable data formats.',
    },
    faq: [
      { q: 'How does JSON to YAML work?', a: 'The tool parses your JSON and outputs equivalent YAML with proper indentation and syntax.' },
    ],
    relatedTools: ['yaml-to-json', 'json-formatter', 'yaml-formatter'],
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    route: '/csv-to-json',
    category: 'json',
    description: 'Parse CSV and convert to JSON array. First row becomes object keys.',
    shortDescription: 'Convert CSV to JSON',
    icon: '⇄',
    keywords: ['csv', 'json', 'convert', 'import', 'converter'],
    sampleInput: 'name,age\nJohn,30\nJane,25',
    sampleOutput: '[{"name":"John","age":"30"},{"name":"Jane","age":"25"}]',
    seoH1: 'CSV to JSON Converter — Convert CSV to JSON Online Free',
    seoExtra: {
      comparisonTitle: 'CSV vs JSON',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Import spreadsheet data to APIs', 'Convert exports to JSON format'],
      longDescription: 'Parse CSV files and convert to JSON arrays with headers as keys.',
    },
    faq: [
      { q: 'How does CSV to JSON work?', a: 'The first row defines property names. Each subsequent row becomes an object with those keys.' },
    ],
    relatedTools: ['json-to-csv', 'json-formatter', 'json-to-yaml'],
  },
  {
    id: 'json-diff',
    name: 'JSON Diff',
    route: '/json-diff',
    category: 'json',
    description: 'Compare two JSON objects and see differences. Paste both JSON blobs separated by "---" on its own line.',
    shortDescription: 'Compare two JSON objects',
    icon: '⟷',
    keywords: ['json diff', 'json compare', 'compare json', 'json difference'],
    sampleInput: '{"name":"John","age":30}\n---\n{"name":"John","age":31,"city":"NYC"}',
    sampleOutput: '- age: 30\n+ age: 31\n+ city: "NYC"',
    seoH1: 'JSON Diff — Compare Two JSON Objects Online Free',
    seoExtra: {
      comparisonTitle: 'JSON Diff Output',
      comparisonRows: [
        { label: '+', left: 'Added in second JSON', right: '' },
        { label: '-', left: 'Removed from first JSON', right: '' },
        { label: '~', left: 'Changed between the two', right: '' },
      ],
      commonErrors: ['Use "---" on its own line to separate the two JSON objects', 'Both parts must be valid JSON'],
      useCases: ['Compare API responses', 'Diff config file versions', 'Find changes in JSON exports'],
      longDescription: 'JSON Diff compares two JSON objects and highlights added, removed, and changed keys. Paste the first JSON, then "---" on its own line, then the second JSON. The tool outputs a readable diff: + for added keys, - for removed, ~ for changed values. Nested objects are compared recursively. Use it to compare API responses, config versions, or any JSON data. All processing runs in your browser.',
    },
    faq: [
      { q: 'How do I use JSON Diff?', a: 'Paste the first JSON object, then "---" on its own line, then the second JSON object. Click Run to see the differences.' },
      { q: 'What does +, -, and ~ mean?', a: '+ means the key was added in the second JSON, - means it was removed, ~ means the value changed.' },
      { q: 'Does it support nested objects?', a: 'Yes. Nested objects are compared recursively, and differences are shown with dot notation paths.' },
      { q: 'Is my data sent to a server?', a: 'No. The diff runs entirely in your browser. Your JSON never leaves your device.' },
      { q: 'Can I compare arrays?', a: 'Arrays are compared as whole values. If they differ, the change is shown. For detailed array diffing, consider flattening to objects first.' },
    ],
    relatedTools: ['json-formatter', 'json-validator', 'json-viewer'],
  },
  {
    id: 'json-schema-generator',
    name: 'JSON Schema Generator',
    route: '/json-schema-generator',
    category: 'json',
    description: 'Infer JSON Schema from sample JSON. Generates type, properties, and required fields.',
    shortDescription: 'Generate JSON Schema from JSON',
    icon: '◈',
    keywords: ['json', 'schema', 'generate', 'infer', 'validator'],
    sampleInput: '{"name":"John","age":30}',
    sampleOutput: '{"type":"object","properties":{"name":{"type":"string"},"age":{"type":"number"}},"required":["name","age"]}',
    seoH1: 'JSON Schema Generator — Infer Schema from JSON Online Free',
    seoExtra: {
      comparisonTitle: 'JSON vs JSON Schema',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Generate schemas for API validation', 'Document data structures'],
      longDescription: 'Analyze JSON sample data and generate a JSON Schema that describes its structure.',
    },
    faq: [
      { q: 'What is JSON Schema?', a: 'JSON Schema is a vocabulary for annotating and validating JSON documents.' },
    ],
    relatedTools: ['json-formatter', 'json-validator', 'json-to-xml'],
  },
  // ─── YAML Cluster ─────────────────────────────────────────────
  {
    id: 'yaml-formatter',
    name: 'YAML Formatter',
    route: '/yaml-formatter',
    category: 'yaml',
    description: 'Format and beautify YAML with consistent 2-space indentation.',
    shortDescription: 'Format YAML with proper indentation',
    icon: 'Y',
    keywords: ['yaml', 'formatter', 'beautify', 'prettify', 'format'],
    sampleInput: 'name: John\nage: 30\naddress:\n  city: NYC',
    sampleOutput: 'name: John\nage: 30\naddress:\n  city: NYC',
    seoH1: 'YAML Formatter — Beautify YAML Online Free',
    seoExtra: {
      comparisonTitle: 'Formatted vs Compact YAML',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Format config files', 'Clean up YAML output'],
      longDescription: 'Format YAML files with proper indentation and line breaks.',
    },
    faq: [
      { q: 'What is YAML?', a: 'YAML is a human-readable data serialization format often used for configuration files.' },
    ],
    relatedTools: ['yaml-to-json', 'json-to-yaml', 'json-formatter'],
  },
  {
    id: 'yaml-to-json',
    name: 'YAML to JSON',
    route: '/yaml-to-json',
    category: 'yaml',
    description: 'Convert YAML to JSON. Parse YAML and output equivalent JSON.',
    shortDescription: 'Convert YAML to JSON',
    icon: '⇄',
    keywords: ['yaml', 'json', 'convert', 'converter'],
    sampleInput: 'name: John\nage: 30',
    sampleOutput: '{\n  "name": "John",\n  "age": 30\n}',
    seoH1: 'YAML to JSON Converter — Convert YAML to JSON Online Free',
    seoExtra: {
      comparisonTitle: 'YAML vs JSON',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Use YAML configs in JavaScript', 'Convert Kubernetes manifests to JSON'],
      longDescription: 'Convert YAML configuration to JSON for use in APIs and applications.',
    },
    faq: [
      { q: 'How does YAML to JSON work?', a: 'The tool parses YAML using js-yaml and outputs the equivalent JSON structure.' },
    ],
    relatedTools: ['json-to-yaml', 'yaml-formatter', 'json-formatter'],
  },
  // ─── XML Cluster ──────────────────────────────────────────────
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    route: '/xml-formatter',
    category: 'xml',
    description: 'Format XML with proper indentation for readability.',
    shortDescription: 'Format and beautify XML',
    icon: '<>',
    keywords: ['xml', 'formatter', 'beautify', 'prettify', 'format'],
    sampleInput: '<root><item>a</item><item>b</item></root>',
    sampleOutput: '<root>\n  <item>a</item>\n  <item>b</item>\n</root>',
    seoH1: 'XML Formatter — Beautify XML Online Free',
    seoExtra: {
      comparisonTitle: 'Formatted vs Minified XML',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Format SOAP responses', 'Read XML config files'],
      longDescription: 'Format XML documents with proper indentation for easy reading.',
    },
    faq: [
      { q: 'What is XML?', a: 'XML is a markup language for storing and transporting structured data.' },
    ],
    relatedTools: ['xml-validator', 'xml-to-json', 'json-to-xml'],
  },
  {
    id: 'xml-validator',
    name: 'XML Validator',
    route: '/xml-validator',
    category: 'xml',
    description: 'Validate XML syntax. Check for well-formed XML and report errors.',
    shortDescription: 'Validate XML syntax',
    icon: '✓',
    keywords: ['xml', 'validator', 'validate', 'check', 'syntax'],
    sampleInput: '<root><item>test</item></root>',
    sampleOutput: '✓ Valid XML',
    seoH1: 'XML Validator — Validate XML Online Free',
    seoExtra: {
      comparisonTitle: 'XML Validator vs XML Formatter',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Debug XML responses', 'Verify config files'],
      longDescription: 'Validate XML documents for correct syntax and structure.',
    },
    faq: [
      { q: 'What does XML validation check?', a: 'It checks for well-formed XML: balanced tags, proper escaping, valid structure.' },
    ],
    relatedTools: ['xml-formatter', 'xml-to-json', 'json-validator'],
  },
  {
    id: 'xml-to-json',
    name: 'XML to JSON',
    route: '/xml-to-json',
    category: 'xml',
    description: 'Convert XML to JSON. Parse XML and output equivalent JSON structure.',
    shortDescription: 'Convert XML to JSON',
    icon: '⇄',
    keywords: ['xml', 'json', 'convert', 'converter'],
    sampleInput: '<root><name>John</name><age>30</age></root>',
    sampleOutput: '{\n  "root": {\n    "name": "John",\n    "age": "30"\n  }\n}',
    seoH1: 'XML to JSON Converter — Convert XML to JSON Online Free',
    seoExtra: {
      comparisonTitle: 'XML vs JSON',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Convert SOAP to REST', 'Process XML in JavaScript'],
      longDescription: 'Convert XML documents to JSON for use in modern applications.',
    },
    faq: [
      { q: 'How does XML to JSON work?', a: 'Elements become objects, text content is preserved, attributes are prefixed with @.' },
    ],
    relatedTools: ['json-to-xml', 'xml-formatter', 'json-formatter'],
  },
  // ─── Security Cluster ─────────────────────────────────────────
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    route: '/jwt-decoder',
    category: 'security',
    description: 'Decode JWT tokens. View header and payload as formatted JSON.',
    shortDescription: 'Decode JWT tokens',
    icon: '🔓',
    keywords: ['jwt', 'decode', 'token', 'header', 'payload'],
    sampleInput: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIn0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c',
    sampleOutput: '{"header":{"alg":"HS256","typ":"JWT"},"payload":{"sub":"1234567890","name":"John Doe"}}',
    seoH1: 'JWT Decoder — Decode JWT Tokens Online Free',
    seoExtra: {
      comparisonTitle: 'JWT Structure',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Debug authentication tokens', 'Inspect token claims'],
      longDescription: 'Decode JWT (JSON Web Token) header and payload without verifying the signature.',
    },
    faq: [
      { q: 'Does this verify the JWT signature?', a: 'No. This tool only decodes the base64url-encoded header and payload for inspection.' },
    ],
    relatedTools: ['base64', 'json-formatter', 'json-validator'],
  },
  // ─── High-traffic SEO tools ─────────────────────────────────────
  {
    id: 'json-viewer',
    name: 'JSON Viewer',
    route: '/json-viewer',
    category: 'json',
    description: 'View and explore JSON data with an interactive tree. Format, validate, and navigate nested structures online.',
    shortDescription: 'View JSON in tree format',
    icon: '👁',
    keywords: ['json viewer', 'json tree', 'json explorer', 'view json online'],
    sampleInput: '{"user":{"name":"John","roles":["admin","user"]}}',
    sampleOutput: '{\n  "user": {\n    "name": "John",\n    "roles": ["admin", "user"]\n  }\n}',
    seoH1: 'JSON Viewer — View & Explore JSON Online Free',
    seoExtra: {
      comparisonTitle: 'JSON Viewer vs Plain Text',
      comparisonRows: [
        { label: 'Structure', left: 'Collapsible tree view', right: 'Flat text' },
        { label: 'Navigation', left: 'Expand/collapse nodes', right: 'Scroll only' },
        { label: 'Syntax', left: 'Highlighted + validated', right: 'Raw text' },
      ],
      commonErrors: ['Invalid JSON prevents tree rendering', 'Ensure proper quote and comma usage'],
      useCases: ['Explore API responses', 'Debug nested configs', 'Inspect JSON structure'],
      longDescription: 'JSON Viewer displays your JSON data as an interactive, collapsible tree. Paste minified or formatted JSON and use the Tree view in the output panel to expand and collapse objects and arrays. This makes it easy to navigate large JSON structures without scrolling through raw text. The tool formats your JSON with proper indentation and validates syntax, so you can quickly spot structural issues. All processing runs in your browser—your data never leaves your device.',
    },
    faq: [
      { q: 'What is a JSON viewer?', a: 'A JSON viewer formats and displays JSON in a navigable tree structure so you can expand and collapse nested objects and arrays.' },
      { q: 'How do I view JSON in tree format?', a: 'Paste your JSON into the editor, click Run, then toggle the Tree button in the output panel to see the collapsible view.' },
      { q: 'Can I view invalid JSON?', a: 'No. The viewer requires valid JSON. Use our JSON Validator to fix syntax errors first.' },
      { q: 'Is my JSON data secure?', a: 'Yes. All processing happens in your browser. No data is sent to any server.' },
      { q: 'What is JSON?', a: 'JSON (JavaScript Object Notation) is a lightweight data format used for APIs, configs, and data storage.' },
    ],
    relatedTools: ['json-formatter', 'json-validator', 'json-to-xml'],
  },
  {
    id: 'json-parser',
    name: 'JSON Parser',
    route: '/json-parser',
    category: 'json',
    description: 'Parse JSON strings online. Validate syntax, format output, and get structured results instantly.',
    shortDescription: 'Parse and validate JSON online',
    icon: '⚙',
    keywords: ['json parser', 'parse json', 'json parser online', 'parse json string'],
    sampleInput: '{"key":"value","count":42}',
    sampleOutput: '{\n  "key": "value",\n  "count": 42\n}',
    seoH1: 'JSON Parser — Parse & Validate JSON Online Free',
    seoExtra: {
      comparisonTitle: 'JSON Parser vs Manual Parsing',
      comparisonRows: [
        { label: 'Speed', left: 'Instant in-browser', right: 'Manual debugging' },
        { label: 'Errors', left: 'Clear error messages', right: 'Obscure stack traces' },
        { label: 'Output', left: 'Formatted + validated', right: 'Depends on code' },
      ],
      commonErrors: ['Trailing commas', 'Unquoted keys', 'Single quotes', 'Missing brackets'],
      useCases: ['Parse API responses', 'Validate config files', 'Debug JSON strings'],
      longDescription: 'The JSON Parser parses your JSON string and returns formatted, validated output. It uses the native browser JSON engine to ensure compatibility with standard JSON. If parsing fails, you get a clear error message to fix the issue. The parser handles all JSON types—objects, arrays, strings, numbers, booleans, and null. Use it to quickly verify JSON from APIs, configs, or logs. Everything runs client-side for speed and privacy.',
    },
    faq: [
      { q: 'What is a JSON parser?', a: 'A JSON parser reads a JSON string and converts it into a structured format, validating syntax and reporting errors.' },
      { q: 'How do I parse JSON online?', a: 'Paste your JSON string into the editor and click Run. Valid JSON will be formatted; invalid JSON will show an error.' },
      { q: 'Does the parser support all JSON types?', a: 'Yes. Objects, arrays, strings, numbers, booleans, and null are all supported.' },
      { q: 'Why does my JSON fail to parse?', a: 'Common causes: trailing commas, unquoted keys, single quotes instead of double quotes, or missing brackets.' },
      { q: 'Is the JSON parser free?', a: 'Yes. The tool is free, runs in your browser, and requires no sign-up.' },
    ],
    relatedTools: ['json-validator', 'json-formatter', 'json-viewer'],
  },
  {
    id: 'json-pretty-print',
    name: 'JSON Pretty Print',
    route: '/json-pretty-print',
    category: 'json',
    description: 'Pretty print JSON with consistent indentation. Make minified JSON readable in one click.',
    shortDescription: 'Pretty print JSON with indentation',
    icon: '✨',
    keywords: ['json pretty print', 'pretty print json', 'json beautifier', 'format json'],
    sampleInput: '{"a":1,"b":[2,3],"c":{"d":4}}',
    sampleOutput: '{\n  "a": 1,\n  "b": [2, 3],\n  "c": {\n    "d": 4\n  }\n}',
    seoH1: 'JSON Pretty Print — Beautify JSON Online Free',
    seoExtra: {
      comparisonTitle: 'Pretty Print vs Minified',
      comparisonRows: [
        { label: 'Readability', left: 'Indented, one item per line', right: 'Single line' },
        { label: 'Size', left: 'Larger', right: 'Smallest' },
        { label: 'Use', left: 'Debugging, editing', right: 'APIs, storage' },
      ],
      commonErrors: ['Invalid JSON', 'Trailing commas', 'Unquoted keys'],
      useCases: ['Read API responses', 'Edit config files', 'Debug JSON data'],
      longDescription: 'JSON Pretty Print transforms minified or compressed JSON into a human-readable format with 2-space indentation and line breaks. Paste any valid JSON—whether from an API, log file, or config—and get clean output instantly. The tool preserves all data and structure while improving readability. Perfect for development and debugging. All processing is client-side.',
    },
    faq: [
      { q: 'What is pretty print JSON?', a: 'Pretty printing adds indentation and line breaks to JSON so it is easy to read and edit.' },
      { q: 'What indentation does it use?', a: '2 spaces per nesting level, which is a common standard.' },
      { q: 'Does it change my data?', a: 'No. Only whitespace is added. Data and structure remain identical.' },
      { q: 'Can I pretty print invalid JSON?', a: 'No. Fix syntax errors first with our JSON Validator.' },
      { q: 'Is it free?', a: 'Yes. Free, no sign-up, runs entirely in your browser.' },
    ],
    relatedTools: ['json-formatter', 'json-minifier', 'json-viewer'],
  },
  {
    id: 'html-formatter',
    name: 'HTML Formatter',
    route: '/html-formatter',
    category: 'markup',
    description: 'Format and beautify HTML with proper indentation. Make minified HTML readable online.',
    shortDescription: 'Format and beautify HTML',
    icon: '<>',
    keywords: ['html formatter', 'format html', 'html beautifier', 'html formatter online'],
    sampleInput: '<div><span>Hello</span><p>World</p></div>',
    sampleOutput: '<div>\n  <span>Hello</span>\n  <p>World</p>\n</div>',
    seoH1: 'HTML Formatter — Beautify HTML Online Free',
    seoExtra: {
      comparisonTitle: 'Formatted vs Minified HTML',
      comparisonRows: [
        { label: 'Readability', left: 'Indented tags', right: 'Single line' },
        { label: 'Editing', left: 'Easy to modify', right: 'Hard to read' },
        { label: 'Size', left: 'Larger', right: 'Smaller' },
      ],
      commonErrors: ['Unclosed tags', 'Invalid nesting', 'Special characters in attributes'],
      useCases: ['Format minified HTML', 'Prepare HTML for review', 'Debug markup structure'],
      longDescription: 'The HTML Formatter adds proper indentation and line breaks to minified or compact HTML. Paste your HTML—whether from a CMS, template, or scraper—and get clean, readable output. The tool parses the HTML and reformats it with consistent indentation. Useful for code review, debugging, and learning HTML structure. All processing runs in your browser.',
    },
    faq: [
      { q: 'What is an HTML formatter?', a: 'An HTML formatter adds indentation and line breaks to HTML to make it readable.' },
      { q: 'Does it fix invalid HTML?', a: 'The browser parser may correct some errors, but malformed HTML can produce unexpected output.' },
      { q: 'Will formatting change how the page renders?', a: 'No. Whitespace changes do not affect HTML rendering.' },
      { q: 'Is my HTML sent to a server?', a: 'No. Formatting happens entirely in your browser.' },
      { q: 'Can I format large HTML files?', a: 'Yes. The tool handles large inputs limited only by browser memory.' },
    ],
    relatedTools: ['xml-formatter', 'json-formatter', 'xml-validator'],
  },
  {
    id: 'url-encode',
    name: 'URL Encoder',
    route: '/url-encode',
    category: 'encoding',
    description: 'Encode text for use in URLs. Convert spaces and special characters to percent-encoded format.',
    shortDescription: 'Encode text for URLs',
    icon: '%',
    keywords: ['url encode', 'url encoder', 'percent encode', 'encode url'],
    sampleInput: 'Hello World! How are you?',
    sampleOutput: 'Hello%20World!%20How%20are%20you%3F',
    seoH1: 'URL Encoder — Encode Text for URLs Online Free',
    seoExtra: {
      comparisonTitle: 'URL Encoded vs Plain Text',
      comparisonRows: [
        { label: 'Spaces', left: '%20', right: ' ' },
        { label: 'Special chars', left: '%XX hex', right: 'Raw character' },
        { label: 'Use', left: 'Query params, paths', right: 'Display only' },
      ],
      commonErrors: ['Double encoding', 'Wrong character set', 'Missing encoding in APIs'],
      useCases: ['Build query strings', 'Encode form data', 'Create safe URLs'],
      longDescription: 'URL Encoder converts text into percent-encoded format for safe use in URLs. Spaces become %20, special characters like & and = become %26 and %3D. This is essential when building query strings, passing parameters in URLs, or encoding form data. The tool uses the standard encodeURIComponent function. All encoding happens in your browser.',
    },
    faq: [
      { q: 'What is URL encoding?', a: 'URL encoding converts characters into %XX format so they can be safely used in URLs.' },
      { q: 'When should I use URL encoding?', a: 'When building query strings, passing parameters in URLs, or encoding form data for submission.' },
      { q: 'What about spaces?', a: 'Spaces are encoded as %20 (or + in application/x-www-form-urlencoded).' },
      { q: 'Is this the same as Base64?', a: 'No. URL encoding is percent-encoding; Base64 is a different binary-to-text encoding.' },
      { q: 'Is my data secure?', a: 'Yes. Encoding runs in your browser. No data is sent to any server.' },
    ],
    relatedTools: ['url-decode', 'base64', 'json-formatter'],
  },
  {
    id: 'url-decode',
    name: 'URL Decoder',
    route: '/url-decode',
    category: 'encoding',
    description: 'Decode URL-encoded strings. Convert percent-encoded text back to plain text.',
    shortDescription: 'Decode URL-encoded strings',
    icon: '%',
    keywords: ['url decode', 'url decoder', 'percent decode', 'decode url'],
    sampleInput: 'Hello%20World!%20How%20are%20you%3F',
    sampleOutput: 'Hello World! How are you?',
    seoH1: 'URL Decoder — Decode URL-Encoded Text Online Free',
    seoExtra: {
      comparisonTitle: 'Encoded vs Decoded',
      comparisonRows: [
        { label: '%20', left: 'Encoded space', right: ' ' },
        { label: '%3F', left: 'Encoded ?', right: '?' },
        { label: 'Use', left: 'In URLs', right: 'Readable text' },
      ],
      commonErrors: ['Invalid % sequence', 'Double-encoded input', 'Malformed hex'],
      useCases: ['Decode query params', 'Read encoded URLs', 'Debug URL issues'],
      longDescription: 'URL Decoder reverses percent-encoding. Paste a URL-encoded string and get the original text. Handles %20 (space), %2B (+), and all standard percent-encoded sequences. Useful when debugging URLs, parsing query parameters, or understanding encoded data. Runs entirely in your browser.',
    },
    faq: [
      { q: 'What is URL decoding?', a: 'URL decoding converts percent-encoded sequences (e.g. %20) back to their original characters.' },
      { q: 'What does %20 mean?', a: '%20 is the encoded form of a space character.' },
      { q: 'Why does decoding fail?', a: 'Invalid % sequences (e.g. %2G) or truncated input can cause errors.' },
      { q: 'Does it handle + as space?', a: 'Yes. Plus signs are decoded as spaces, per application/x-www-form-urlencoded.' },
      { q: 'Is it free?', a: 'Yes. Free, no sign-up, 100% client-side.' },
    ],
    relatedTools: ['url-encode', 'base64', 'json-formatter'],
  },
  {
    id: 'base64-encode',
    name: 'Base64 Encoder',
    route: '/base64-encode',
    category: 'encoding',
    description: 'Encode text or binary data to Base64. Safe for URLs, JSON, and email.',
    shortDescription: 'Encode to Base64',
    icon: 'B64',
    keywords: ['base64 encode', 'base64 encoder', 'encode base64', 'base64 encode online'],
    sampleInput: 'Hello, World!',
    sampleOutput: 'SGVsbG8sIFdvcmxkIQ==',
    seoH1: 'Base64 Encoder — Encode to Base64 Online Free',
    seoExtra: {
      comparisonTitle: 'Base64 vs Plain Text',
      comparisonRows: [
        { label: 'Chars', left: 'A-Z, a-z, 0-9, +, /', right: 'Full Unicode' },
        { label: 'Size', left: '~33% larger', right: 'Original' },
        { label: 'Use', left: 'Data URIs, MIME', right: 'Direct storage' },
      ],
      commonErrors: ['Not encryption', 'Binary data encoding', 'Unicode handling'],
      useCases: ['Data URIs', 'API tokens', 'MIME encoding', 'Embed binary in JSON'],
      longDescription: 'Base64 Encoder converts text and binary data into Base64 format. Use it for data URIs, MIME email attachments, API authentication, and embedding binary in JSON. The output uses only safe ASCII characters. UTF-8 text is fully supported. Encoding runs in your browser—no server involvement.',
    },
    faq: [
      { q: 'What is Base64 encoding?', a: 'Base64 converts binary data into printable ASCII characters using a 64-character alphabet.' },
      { q: 'Is Base64 encryption?', a: 'No. Base64 is encoding, not encryption. Anyone can decode it.' },
      { q: 'Does it support UTF-8?', a: 'Yes. Multi-byte characters are properly encoded.' },
      { q: 'Why is the output larger?', a: 'Base64 uses 4 characters for every 3 bytes of input, about 33% size increase.' },
      { q: 'Is it free?', a: 'Yes. Free, no sign-up, runs in your browser.' },
    ],
    relatedTools: ['base64-decode', 'url-encode', 'jwt-decoder'],
  },
  {
    id: 'base64-decode',
    name: 'Base64 Decoder',
    route: '/base64-decode',
    category: 'encoding',
    description: 'Decode Base64 strings to plain text. Reverse Base64 encoding instantly.',
    shortDescription: 'Decode Base64 to text',
    icon: 'B64',
    keywords: ['base64 decode', 'base64 decoder', 'decode base64', 'base64 decode online'],
    sampleInput: 'SGVsbG8sIFdvcmxkIQ==',
    sampleOutput: 'Hello, World!',
    seoH1: 'Base64 Decoder — Decode Base64 Online Free',
    seoExtra: {
      comparisonTitle: 'Base64 vs Decoded',
      comparisonRows: [
        { label: 'Input', left: 'Base64 string', right: 'Plain text' },
        { label: 'Output', left: 'Original data', right: 'N/A' },
        { label: 'Use', left: 'Reverse encoding', right: 'N/A' },
      ],
      commonErrors: ['Invalid characters', 'Missing padding', 'Wrong encoding'],
      useCases: ['Decode data URIs', 'Read JWT payloads', 'Extract embedded data'],
      longDescription: 'Base64 Decoder converts Base64 strings back to their original form. Paste a Base64-encoded string and get the decoded output. Handles UTF-8 text and binary data. Useful for debugging JWT tokens, data URIs, and API responses. All decoding happens in your browser.',
    },
    faq: [
      { q: 'What is Base64 decoding?', a: 'Base64 decoding reverses the encoding process, converting Base64 strings back to original data.' },
      { q: 'Why does decoding fail?', a: 'Invalid characters, incorrect padding, or corrupted input cause failures.' },
      { q: 'Can it decode images?', a: 'It decodes to binary/text. For images, you would need to handle the binary output.' },
      { q: 'Is it secure?', a: 'Decoding runs in your browser. Your data is not sent anywhere.' },
      { q: 'Is it free?', a: 'Yes. Free, no sign-up, 100% client-side.' },
    ],
    relatedTools: ['base64-encode', 'jwt-decoder', 'url-decode'],
  },
  // JSON-to-language converters (Phase 1)
  {
    id: 'json-to-typescript',
    name: 'JSON to TypeScript',
    route: '/json-to-typescript',
    category: 'json',
    description: 'Generate TypeScript interfaces from JSON. Paste JSON and get type definitions for your frontend or API.',
    shortDescription: 'Convert JSON to TypeScript types',
    icon: 'TS',
    keywords: ['json to typescript', 'json to interface', 'typescript from json', 'generate types'],
    sampleInput: '{"name":"John","age":30,"active":true}',
    sampleOutput: 'interface Root {\n  name: string;\n  age: number;\n  active: boolean;\n}\n',
    seoH1: 'JSON to TypeScript — Generate TypeScript Interfaces from JSON Online',
    seoExtra: {
      comparisonTitle: '',
      comparisonRows: [],
      commonErrors: ['Invalid JSON', 'Trailing commas', 'Single quotes', 'Unquoted keys'],
      useCases: ['API response types', 'Frontend models', 'Documentation', 'Type-safe clients'],
      longDescription: 'Convert JSON to TypeScript interfaces in one click. Paste a sample JSON object and get a TypeScript interface or type definition. Use it for API contracts, frontend models, or documentation. The tool infers types from your data and outputs ready-to-use code. All processing runs in your browser—no data is sent to any server. Part of the formatterjson.org developer data tools platform.',
    },
    faq: [
      { q: 'What does JSON to TypeScript do?', a: 'It takes a JSON object and generates TypeScript interface or type definitions so you can use type-safe code with that structure.' },
      { q: 'Is the output ready to use?', a: 'Yes. Copy the generated interface into your project. You may want to rename "Root" to match your domain.' },
      { q: 'Does it handle nested objects?', a: 'Yes. Nested objects are inlined as object types. For very deep structures you might refactor into separate interfaces.' },
      { q: 'Is my JSON sent to a server?', a: 'No. Conversion runs entirely in your browser. Your data never leaves your device.' },
      { q: 'Can I use this for APIs?', a: 'Yes. Paste a sample API response to generate types for your client or tests.' },
    ],
    relatedTools: ['json-formatter', 'json-validator', 'json-schema-generator'],
  },
  {
    id: 'json-to-python',
    name: 'JSON to Python',
    route: '/json-to-python',
    category: 'json',
    description: 'Generate Python classes or type hints from JSON. Convert JSON structure to Python code instantly.',
    shortDescription: 'Convert JSON to Python',
    icon: 'Py',
    keywords: ['json to python', 'python from json', 'json to class', 'python dataclass'],
    sampleInput: '{"name":"John","age":30}',
    sampleOutput: 'from typing import Any\n\nclass Root:\n    name: str\n    age: float\n',
    seoH1: 'JSON to Python — Generate Python from JSON Online Free',
    seoExtra: {
      comparisonTitle: '',
      comparisonRows: [],
      commonErrors: ['Invalid JSON', 'Trailing commas', 'Single quotes'],
      useCases: ['API clients', 'Data models', 'Config parsing', 'Scripts'],
      longDescription: 'Generate Python class definitions from JSON. Paste a JSON object and get Python code with type hints. Useful for API clients, data pipelines, and config handling. All conversion runs in your browser. Part of the formatterjson.org developer data tools.',
    },
    faq: [
      { q: 'What does JSON to Python output?', a: 'It generates a Python class with attributes matching your JSON keys and inferred types (str, float, bool, list, dict).' },
      { q: 'Can I use it with dataclasses?', a: 'The output is a simple class. You can adapt it to use dataclasses or Pydantic as needed.' },
      { q: 'Is my data sent to a server?', a: 'No. Conversion runs entirely in your browser.' },
      { q: 'Does it handle nested JSON?', a: 'Yes. Nested objects are represented as dict or nested structures.' },
      { q: 'Is it free?', a: 'Yes. Free, no sign-up, 100% client-side.' },
    ],
    relatedTools: ['json-formatter', 'json-validator', 'json-schema-generator'],
  },
  {
    id: 'json-to-java',
    name: 'JSON to Java',
    route: '/json-to-java',
    category: 'json',
    description: 'Generate Java classes from JSON. Convert JSON to POJOs or DTOs for your backend or Android app.',
    shortDescription: 'Convert JSON to Java',
    icon: 'J',
    keywords: ['json to java', 'java from json', 'pojo from json', 'json to class java'],
    sampleInput: '{"name":"John","age":30}',
    sampleOutput: 'public class Root {\n    private String name;\n    private Double age;\n}\n',
    seoH1: 'JSON to Java — Generate Java Classes from JSON Online',
    seoExtra: {
      comparisonTitle: '',
      comparisonRows: [],
      commonErrors: ['Invalid JSON', 'Trailing commas'],
      useCases: ['REST clients', 'Android models', 'DTOs', 'Serialization'],
      longDescription: 'Convert JSON to Java class definitions. Paste JSON and get Java fields and types. Use for REST API DTOs, Android models, or backend services. All processing in your browser. Part of formatterjson.org developer tools.',
    },
    faq: [
      { q: 'What does JSON to Java output?', a: 'It generates a Java class with private fields and types inferred from your JSON (String, Double, Boolean, List, Map).' },
      { q: 'Can I add getters/setters?', a: 'The tool outputs fields. You can use an IDE or Lombok to generate getters and setters.' },
      { q: 'Is my JSON sent to a server?', a: 'No. Conversion runs entirely in your browser.' },
      { q: 'Does it support Jackson annotations?', a: 'Output is plain Java. You can add @JsonProperty or other annotations manually.' },
      { q: 'Is it free?', a: 'Yes. Free, no sign-up.' },
    ],
    relatedTools: ['json-formatter', 'json-validator', 'json-schema-generator'],
  },
  {
    id: 'json-to-go',
    name: 'JSON to Go',
    route: '/json-to-go',
    category: 'json',
    description: 'Generate Go structs from JSON. Convert JSON to Go struct definitions with json tags.',
    shortDescription: 'Convert JSON to Go struct',
    icon: 'Go',
    keywords: ['json to go', 'go struct from json', 'golang json'],
    sampleInput: '{"name":"John","age":30}',
    sampleOutput: 'type Root struct {\n\tName string `json:"name"`\n\tAge  float64 `json:"age"`\n}\n',
    seoH1: 'JSON to Go — Generate Go Structs from JSON Online',
    seoExtra: {
      comparisonTitle: '',
      comparisonRows: [],
      commonErrors: ['Invalid JSON'],
      useCases: ['API unmarshaling', 'Config structs', 'CLI tools'],
      longDescription: 'Convert JSON to Go struct definitions with json struct tags. Paste JSON and get Go code. Use for API clients, config parsing, or any Go project. Runs in your browser. Part of formatterjson.org.',
    },
    faq: [
      { q: 'What does JSON to Go output?', a: 'It generates a Go struct with fields and json tags matching your JSON keys.' },
      { q: 'Is the output ready to use?', a: 'Yes. Copy into your Go file. You may want to rename the struct.' },
      { q: 'Is my data sent to a server?', a: 'No. Conversion runs in your browser.' },
      { q: 'Does it handle nested objects?', a: 'Yes. Nested objects become nested structs or map[string]interface{}.' },
      { q: 'Is it free?', a: 'Yes. Free, no sign-up.' },
    ],
    relatedTools: ['json-formatter', 'json-validator', 'json-schema-generator'],
  },
  {
    id: 'json-to-csharp',
    name: 'JSON to C#',
    route: '/json-to-csharp',
    category: 'json',
    description: 'Generate C# classes from JSON. Convert JSON to C# POCOs or DTOs for .NET apps.',
    shortDescription: 'Convert JSON to C#',
    icon: 'C#',
    keywords: ['json to csharp', 'json to c#', 'c# class from json', 'poco from json'],
    sampleInput: '{"name":"John","age":30}',
    sampleOutput: 'public class Root\n{\n    public string Name { get; set; }\n    public double Age { get; set; }\n}\n',
    seoH1: 'JSON to C# — Generate C# Classes from JSON Online',
    seoExtra: {
      comparisonTitle: '',
      comparisonRows: [],
      commonErrors: ['Invalid JSON'],
      useCases: ['.NET APIs', 'DTOs', 'Xamarin/MAUI', 'Unity'],
      longDescription: 'Convert JSON to C# class definitions with properties. Use for .NET API clients, DTOs, or mobile apps. All processing in your browser. Part of formatterjson.org.',
    },
    faq: [
      { q: 'What does JSON to C# output?', a: 'It generates a C# class with public properties and types inferred from your JSON.' },
      { q: 'Can I use it with System.Text.Json?', a: 'Yes. The generated classes work with System.Text.Json or Newtonsoft.Json.' },
      { q: 'Is my JSON sent to a server?', a: 'No. Conversion runs in your browser.' },
      { q: 'Is it free?', a: 'Yes. Free, no sign-up.' },
    ],
    relatedTools: ['json-formatter', 'json-validator', 'json-schema-generator'],
  },
  {
    id: 'json-to-dart',
    name: 'JSON to Dart',
    route: '/json-to-dart',
    category: 'json',
    description: 'Generate Dart classes from JSON. Convert JSON to Dart models for Flutter or Dart apps.',
    shortDescription: 'Convert JSON to Dart',
    icon: 'D',
    keywords: ['json to dart', 'dart from json', 'flutter model', 'dart class from json'],
    sampleInput: '{"name":"John","age":30}',
    sampleOutput: 'class Root {\n  final String name;\n  final num age;\n  Root({name, age});\n}\n',
    seoH1: 'JSON to Dart — Generate Dart/Flutter Models from JSON Online',
    seoExtra: {
      comparisonTitle: '',
      comparisonRows: [],
      commonErrors: ['Invalid JSON'],
      useCases: ['Flutter apps', 'API models', 'fromJson/toJson'],
      longDescription: 'Convert JSON to Dart class definitions. Use for Flutter or Dart API clients and models. Runs in your browser. Part of formatterjson.org.',
    },
    faq: [
      { q: 'What does JSON to Dart output?', a: 'It generates a Dart class with final fields and a constructor.' },
      { q: 'Does it generate fromJson?', a: 'The tool outputs the class structure. You can add fromJson/toJson manually or with code generation.' },
      { q: 'Is my data sent to a server?', a: 'No. Conversion runs in your browser.' },
      { q: 'Is it free?', a: 'Yes. Free, no sign-up.' },
    ],
    relatedTools: ['json-formatter', 'json-validator', 'json-schema-generator'],
  },
  {
    id: 'json-to-rust',
    name: 'JSON to Rust',
    route: '/json-to-rust',
    category: 'json',
    description: 'Generate Rust structs from JSON. Convert JSON to serde-compatible Rust structs.',
    shortDescription: 'Convert JSON to Rust',
    icon: 'R',
    keywords: ['json to rust', 'rust struct from json', 'serde json'],
    sampleInput: '{"name":"John","age":30}',
    sampleOutput: 'pub struct Root {\n    pub name: String,\n    pub age: f64,\n}\n',
    seoH1: 'JSON to Rust — Generate Rust Structs from JSON Online',
    seoExtra: {
      comparisonTitle: '',
      comparisonRows: [],
      commonErrors: ['Invalid JSON'],
      useCases: ['API clients', 'Config', 'CLI tools'],
      longDescription: 'Convert JSON to Rust struct definitions. Output is compatible with serde. Use for APIs, config, or CLI tools. Runs in your browser. Part of formatterjson.org.',
    },
    faq: [
      { q: 'What does JSON to Rust output?', a: 'It generates a Rust struct with pub fields. You can add #[derive(Deserialize, Serialize)] and use with serde_json.' },
      { q: 'Is my JSON sent to a server?', a: 'No. Conversion runs in your browser.' },
      { q: 'Is it free?', a: 'Yes. Free, no sign-up.' },
    ],
    relatedTools: ['json-formatter', 'json-validator', 'json-schema-generator'],
  },
  {
    id: 'json-to-kotlin',
    name: 'JSON to Kotlin',
    route: '/json-to-kotlin',
    category: 'json',
    description: 'Generate Kotlin data classes from JSON. Convert JSON to Kotlin for Android or backend.',
    shortDescription: 'Convert JSON to Kotlin',
    icon: 'K',
    keywords: ['json to kotlin', 'kotlin from json', 'data class from json'],
    sampleInput: '{"name":"John","age":30}',
    sampleOutput: 'data class Root(\n    val name: String,\n    val age: Double\n)\n',
    seoH1: 'JSON to Kotlin — Generate Kotlin Data Classes from JSON Online',
    seoExtra: {
      comparisonTitle: '',
      comparisonRows: [],
      commonErrors: ['Invalid JSON'],
      useCases: ['Android', 'Ktor', 'Backend Kotlin'],
      longDescription: 'Convert JSON to Kotlin data class definitions. Use for Android, Ktor, or any Kotlin project. Runs in your browser. Part of formatterjson.org.',
    },
    faq: [
      { q: 'What does JSON to Kotlin output?', a: 'It generates a Kotlin data class with properties inferred from your JSON.' },
      { q: 'Is my JSON sent to a server?', a: 'No. Conversion runs in your browser.' },
      { q: 'Is it free?', a: 'Yes. Free, no sign-up.' },
    ],
    relatedTools: ['json-formatter', 'json-validator', 'json-schema-generator'],
  },
  {
    id: 'json-to-swift',
    name: 'JSON to Swift',
    route: '/json-to-swift',
    category: 'json',
    description: 'Generate Swift structs from JSON. Convert JSON to Codable Swift types for iOS or server.',
    shortDescription: 'Convert JSON to Swift',
    icon: 'Sw',
    keywords: ['json to swift', 'swift from json', 'codable from json'],
    sampleInput: '{"name":"John","age":30}',
    sampleOutput: 'struct Root: Codable {\n    let name: String\n    let age: Double\n}\n',
    seoH1: 'JSON to Swift — Generate Swift Structs from JSON Online',
    seoExtra: {
      comparisonTitle: '',
      comparisonRows: [],
      commonErrors: ['Invalid JSON'],
      useCases: ['iOS apps', 'Vapor', 'Codable'],
      longDescription: 'Convert JSON to Swift struct definitions with Codable. Use for iOS, macOS, or server-side Swift. Runs in your browser. Part of formatterjson.org.',
    },
    faq: [
      { q: 'What does JSON to Swift output?', a: 'It generates a Swift struct conforming to Codable with properties from your JSON.' },
      { q: 'Is my JSON sent to a server?', a: 'No. Conversion runs in your browser.' },
      { q: 'Is it free?', a: 'Yes. Free, no sign-up.' },
    ],
    relatedTools: ['json-formatter', 'json-validator', 'json-schema-generator'],
  },
  {
    id: 'json-to-php',
    name: 'JSON to PHP',
    route: '/json-to-php',
    category: 'json',
    description: 'Generate PHP classes from JSON. Convert JSON to PHP classes or DTOs.',
    shortDescription: 'Convert JSON to PHP',
    icon: 'PHP',
    keywords: ['json to php', 'php from json', 'php class from json'],
    sampleInput: '{"name":"John","age":30}',
    sampleOutput: '<?php\n\nclass Root\n{\n    public string $name;\n    public float $age;\n}\n',
    seoH1: 'JSON to PHP — Generate PHP Classes from JSON Online',
    seoExtra: {
      comparisonTitle: '',
      comparisonRows: [],
      commonErrors: ['Invalid JSON'],
      useCases: ['Laravel', 'API responses', 'DTOs'],
      longDescription: 'Convert JSON to PHP class definitions. Use for Laravel, APIs, or any PHP project. Runs in your browser. Part of formatterjson.org.',
    },
    faq: [
      { q: 'What does JSON to PHP output?', a: 'It generates a PHP class with typed properties matching your JSON.' },
      { q: 'Is my JSON sent to a server?', a: 'No. Conversion runs in your browser.' },
      { q: 'Is it free?', a: 'Yes. Free, no sign-up.' },
    ],
    relatedTools: ['json-formatter', 'json-validator', 'json-schema-generator'],
  },
  // JSON utility pages (Phase 2)
  {
    id: 'json-compare',
    name: 'JSON Compare',
    route: '/json-compare',
    category: 'json',
    description: 'Compare two JSON documents side by side. See added, removed, and changed keys.',
    shortDescription: 'Compare two JSON documents',
    icon: '⟷',
    keywords: ['json compare', 'compare json', 'json diff', 'diff json'],
    sampleInput: '{}',
    sampleOutput: 'Paste left and right JSON above.',
    seoH1: 'JSON Compare — Compare Two JSON Documents Online',
    seoExtra: {
      comparisonTitle: '',
      comparisonRows: [],
      commonErrors: ['Invalid JSON in either panel'],
      useCases: ['Config changes', 'API version diff', 'Data migration'],
      longDescription: 'Compare two JSON documents in left and right panels. See a clear diff of added, removed, and changed keys. Useful for config reviews, API changes, and data migration. Runs in your browser. Part of formatterjson.org.',
    },
    faq: [
      { q: 'What is JSON Compare?', a: 'A tool to compare two JSON documents side by side and view differences.' },
      { q: 'Is my data sent to a server?', a: 'No. Comparison runs entirely in your browser.' },
      { q: 'How is it different from JSON Diff?', a: 'Same functionality; JSON Compare is an alternate entry point with the same two-panel interface.' },
    ],
    relatedTools: ['json-diff', 'json-formatter', 'json-validator'],
  },
  {
    id: 'json-sorter',
    name: 'JSON Sorter',
    route: '/json-sorter',
    category: 'json',
    description: 'Sort JSON object keys alphabetically. Get consistent key order for version control or comparison.',
    shortDescription: 'Sort JSON keys',
    icon: '⇅',
    keywords: ['json sort', 'sort json keys', 'json key order'],
    sampleInput: '{"z":1,"a":2,"m":3}',
    sampleOutput: '{\n  "a": 2,\n  "m": 3,\n  "z": 1\n}\n',
    seoH1: 'JSON Sorter — Sort JSON Object Keys Online',
    seoExtra: { comparisonTitle: '', comparisonRows: [], commonErrors: ['Invalid JSON'], useCases: ['Consistent key order', 'Version control', 'Comparison'], longDescription: 'Sort all keys in a JSON object alphabetically. Nested objects are sorted recursively. Useful for consistent diffs and version control. Runs in your browser.' },
    faq: [
      { q: 'What does JSON Sorter do?', a: 'It sorts the keys of your JSON object alphabetically at every level.' },
      { q: 'Does it sort array elements?', a: 'No. Only object keys are sorted; array order is preserved.' },
      { q: 'Is my data sent to a server?', a: 'No. Sorting runs in your browser.' },
    ],
    relatedTools: ['json-formatter', 'json-minifier', 'json-diff'],
  },
  {
    id: 'json-escape',
    name: 'JSON Escape',
    route: '/json-escape',
    category: 'json',
    description: 'Escape a string for safe use inside JSON. Backslashes, quotes, and control characters.',
    shortDescription: 'Escape string for JSON',
    icon: '\\',
    keywords: ['json escape', 'escape json string', 'json string escape'],
    sampleInput: 'Hello "World"',
    sampleOutput: '"Hello \\"World\\""',
    seoH1: 'JSON Escape — Escape String for JSON Online',
    seoExtra: { comparisonTitle: '', comparisonRows: [], commonErrors: [], useCases: ['Building JSON manually', 'Embedding strings'], longDescription: 'Escape a string so it can be safely embedded in JSON. Handles quotes, backslashes, and control characters. Runs in your browser.' },
    faq: [
      { q: 'What does JSON Escape do?', a: 'It takes a plain string and outputs the same string as a valid JSON string value with special characters escaped.' },
      { q: 'Is my data sent to a server?', a: 'No. Escaping runs in your browser.' },
    ],
    relatedTools: ['json-unescape', 'json-formatter', 'json-validator'],
  },
  {
    id: 'json-unescape',
    name: 'JSON Unescape',
    route: '/json-unescape',
    category: 'json',
    description: 'Unescape a JSON string. Convert escaped quotes, backslashes, and control characters back to plain text.',
    shortDescription: 'Unescape JSON string',
    icon: '/',
    keywords: ['json unescape', 'unescape json', 'json decode string'],
    sampleInput: '"Hello \\nWorld"',
    sampleOutput: 'Hello\nWorld',
    seoH1: 'JSON Unescape — Unescape JSON String Online',
    seoExtra: { comparisonTitle: '', comparisonRows: [], commonErrors: ['Invalid escape sequence'], useCases: ['Debugging JSON', 'Extracting strings'], longDescription: 'Unescape a JSON-encoded string to get the original text. Handles \\n, \\t, \\", and \\\\. Runs in your browser.' },
    faq: [
      { q: 'What does JSON Unescape do?', a: 'It reverses JSON string escaping, turning \\n into newline, \\" into quote, etc.' },
      { q: 'Is my data sent to a server?', a: 'No. Unescaping runs in your browser.' },
    ],
    relatedTools: ['json-escape', 'json-formatter'],
  },
  {
    id: 'json-editor',
    name: 'JSON Editor',
    route: '/json-editor',
    category: 'json',
    description: 'Edit and format JSON with syntax highlighting. Beautify and validate as you type.',
    shortDescription: 'Edit and format JSON',
    icon: '✎',
    keywords: ['json editor', 'edit json', 'json format'],
    sampleInput: '{"name":"John"}',
    sampleOutput: '{\n  "name": "John"\n}\n',
    seoH1: 'JSON Editor — Edit and Format JSON Online',
    seoExtra: { comparisonTitle: '', comparisonRows: [], commonErrors: ['Invalid JSON'], useCases: ['Quick edits', 'Format and validate'], longDescription: 'Edit JSON with an IDE-style editor. Format and beautify with one click. Same workflow as the JSON Formatter with focus on editing. Runs in your browser.' },
    faq: [
      { q: 'What is JSON Editor?', a: 'An editor that formats and validates JSON as you work. Same capabilities as the formatter with an editing focus.' },
      { q: 'Is my data sent to a server?', a: 'No. Editing and formatting run in your browser.' },
    ],
    relatedTools: ['json-formatter', 'json-validator', 'json-minifier'],
  },
  {
    id: 'json-to-html-table',
    name: 'JSON to HTML Table',
    route: '/json-to-html-table',
    category: 'json',
    description: 'Convert a JSON array to an HTML table. Generate <table> markup from JSON data.',
    shortDescription: 'JSON to HTML table',
    icon: '⟨⟩',
    keywords: ['json to html table', 'json to table', 'html table from json'],
    sampleInput: '[{"name":"Alice","age":30},{"name":"Bob","age":25}]',
    sampleOutput: '<table>...</table>',
    seoH1: 'JSON to HTML Table — Convert JSON to HTML Table Online',
    seoExtra: { comparisonTitle: '', comparisonRows: [], commonErrors: ['Invalid JSON'], useCases: ['Reports', 'Embed tables in HTML'], longDescription: 'Convert a JSON array of objects into an HTML table. Each object becomes a row; keys become column headers. Runs in your browser.' },
    faq: [
      { q: 'What does JSON to HTML Table do?', a: 'It converts a JSON array of objects into <table>, <thead>, <tbody>, <tr>, <th>, <td> markup.' },
      { q: 'Is my data sent to a server?', a: 'No. Conversion runs in your browser.' },
    ],
    relatedTools: ['json-to-csv', 'json-formatter', 'json-validator'],
  },
  {
    id: 'json-to-sql',
    name: 'JSON to SQL',
    route: '/json-to-sql',
    category: 'json',
    description: 'Convert JSON array to SQL INSERT statements. Generate inserts from JSON data.',
    shortDescription: 'JSON to SQL INSERTs',
    icon: 'SQL',
    keywords: ['json to sql', 'json to insert', 'sql from json'],
    sampleInput: '[{"id":1,"name":"Alice"},{"id":2,"name":"Bob"}]',
    sampleOutput: 'INSERT INTO data (...) VALUES (...);',
    seoH1: 'JSON to SQL — Convert JSON to SQL INSERT Statements Online',
    seoExtra: { comparisonTitle: '', comparisonRows: [], commonErrors: ['Invalid JSON'], useCases: ['Seeding databases', 'Migration scripts'], longDescription: 'Convert a JSON array into SQL INSERT statements. Useful for seeding databases or migration scripts. Table name is configurable in the output. Runs in your browser.' },
    faq: [
      { q: 'What does JSON to SQL output?', a: 'It generates one INSERT statement per object in your JSON array.' },
      { q: 'Can I change the table name?', a: 'The output uses a default table name; you can find-and-replace it in the result.' },
      { q: 'Is my data sent to a server?', a: 'No. Conversion runs in your browser.' },
    ],
    relatedTools: ['json-to-csv', 'json-formatter'],
  },
  {
    id: 'json-to-excel',
    name: 'JSON to Excel',
    route: '/json-to-excel',
    category: 'json',
    description: 'Convert JSON array to CSV for Excel. Export JSON data to spreadsheet-friendly format.',
    shortDescription: 'JSON to CSV/Excel',
    icon: 'XLS',
    keywords: ['json to excel', 'json to csv', 'export json to excel'],
    sampleInput: '[{"a":1,"b":2}]',
    sampleOutput: 'a,b\n1,2\n',
    seoH1: 'JSON to Excel — Convert JSON to CSV for Excel Online',
    seoExtra: { comparisonTitle: '', comparisonRows: [], commonErrors: ['Invalid JSON'], useCases: ['Export to Excel', 'Spreadsheet import'], longDescription: 'Convert a JSON array to CSV format that Excel and other spreadsheets can open. Same as JSON to CSV; use Download to get a .csv file. Runs in your browser.' },
    faq: [
      { q: 'What does JSON to Excel do?', a: 'It converts a JSON array to CSV, which Excel can open. Use the Download button to save as .csv.' },
      { q: 'Is my data sent to a server?', a: 'No. Conversion runs in your browser.' },
    ],
    relatedTools: ['json-to-csv', 'json-to-html-table', 'json-formatter'],
  },
  {
    id: 'json-to-tsv',
    name: 'JSON to TSV',
    route: '/json-to-tsv',
    category: 'json',
    description: 'Convert JSON array to tab-separated values (TSV). Export JSON to TSV format.',
    shortDescription: 'JSON to TSV',
    icon: 'TAB',
    keywords: ['json to tsv', 'json to tab separated', 'tsv from json'],
    sampleInput: '[{"x":1,"y":2}]',
    sampleOutput: 'x\ty\n1\t2\n',
    seoH1: 'JSON to TSV — Convert JSON to Tab-Separated Values Online',
    seoExtra: { comparisonTitle: '', comparisonRows: [], commonErrors: ['Invalid JSON'], useCases: ['Tab-separated export', 'Data exchange'], longDescription: 'Convert a JSON array to TSV (tab-separated values). Useful when your downstream tool expects tabs instead of commas. Runs in your browser.' },
    faq: [
      { q: 'What is TSV?', a: 'Tab-separated values: like CSV but with tab characters between fields.' },
      { q: 'Is my data sent to a server?', a: 'No. Conversion runs in your browser.' },
    ],
    relatedTools: ['json-to-csv', 'json-to-excel', 'json-formatter'],
  },
  {
    id: 'json-to-one-line',
    name: 'JSON to One Line',
    route: '/json-to-one-line',
    category: 'json',
    description: 'Minify JSON to a single line. Remove all whitespace and line breaks.',
    shortDescription: 'JSON to one line',
    icon: '⎯',
    keywords: ['json one line', 'json minify', 'minify json'],
    sampleInput: '{"a": 1, "b": 2}',
    sampleOutput: '{"a":1,"b":2}',
    seoH1: 'JSON to One Line — Minify JSON to Single Line Online',
    seoExtra: { comparisonTitle: '', comparisonRows: [], commonErrors: ['Invalid JSON'], useCases: ['APIs', 'Logs', 'Compact storage'], longDescription: 'Minify JSON to a single line by removing whitespace and newlines. Same as the JSON Minifier. Runs in your browser.' },
    faq: [
      { q: 'What does JSON to One Line do?', a: 'It removes all unnecessary whitespace from JSON so it fits on one line.' },
      { q: 'Is my data sent to a server?', a: 'No. Minification runs in your browser.' },
    ],
    relatedTools: ['json-minifier', 'json-formatter', 'json-validator'],
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    route: '/lorem-ipsum',
    category: 'utility',
    description: 'Generate placeholder Lorem Ipsum text. Enter a number for how many paragraphs (1–20), or leave empty for 3.',
    shortDescription: 'Generate Lorem Ipsum placeholder text',
    icon: '¶',
    keywords: ['lorem ipsum', 'placeholder', 'dummy text', 'generator'],
    sampleInput: '3',
    sampleOutput: 'Lorem ipsum dolor sit amet...',
    seoH1: 'Lorem Ipsum Generator — Free Placeholder Text Online',
    seoExtra: {
      comparisonTitle: 'Lorem Ipsum vs Plain Text',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Mock content for layouts', 'Placeholder in designs', 'Testing typography'],
      longDescription: 'Generate classic Lorem Ipsum placeholder text for designs and layouts. All processing is client-side.',
    },
    faq: [
      { q: 'What is Lorem Ipsum?', a: 'Classic placeholder text used in design and publishing since the 1500s.' },
      { q: 'How many paragraphs can I generate?', a: 'Enter a number from 1 to 20, or leave empty for 3 paragraphs.' },
    ],
    relatedTools: ['uuid-generator', 'random-json-generator'],
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    route: '/uuid-generator',
    category: 'utility',
    description: 'Generate UUIDs (v4). Enter a number for how many to generate (1–50), or leave empty for 1.',
    shortDescription: 'Generate UUID v4 identifiers',
    icon: 'id',
    keywords: ['uuid', 'guid', 'unique id', 'generator'],
    sampleInput: '1',
    sampleOutput: 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx',
    seoH1: 'UUID Generator — Create UUID v4 Online Free',
    seoExtra: {
      comparisonTitle: 'UUID v4',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Unique IDs for records', 'API tokens', 'Distributed systems'],
      longDescription: 'Generate cryptographically random UUID v4 identifiers. Client-side only.',
    },
    faq: [
      { q: 'What is a UUID?', a: 'A Universally Unique Identifier; v4 is random and suitable for most applications.' },
      { q: 'How many can I generate?', a: 'Enter 1–50, or leave empty for a single UUID.' },
    ],
    relatedTools: ['lorem-ipsum', 'jwt-generator'],
  },
  {
    id: 'random-json-generator',
    name: 'Random JSON Generator',
    route: '/random-json-generator',
    category: 'utility',
    description: 'Generate random JSON objects for testing. Enter size (1–20) for number of keys, or leave empty for 5.',
    shortDescription: 'Generate random JSON for testing',
    icon: '{?}',
    keywords: ['random json', 'json generator', 'mock data', 'test data'],
    sampleInput: '5',
    sampleOutput: '{"id": 1, "name": "value_abc", ...}',
    seoH1: 'Random JSON Generator — Create Test Data Online Free',
    seoExtra: {
      comparisonTitle: 'Random JSON',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Testing APIs', 'Mock data', 'Sample payloads'],
      longDescription: 'Generate random JSON objects with mixed types. Client-side only.',
    },
    faq: [
      { q: 'What does the input number do?', a: 'It controls how many top-level keys the generated object has (1–20).' },
    ],
    relatedTools: ['json-formatter', 'lorem-ipsum'],
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    route: '/timestamp-converter',
    category: 'utility',
    description: 'Convert between Unix timestamps and human-readable dates. Enter a timestamp (ms or sec), a date string, or leave empty for "now".',
    shortDescription: 'Convert Unix timestamp to date and back',
    icon: '🕐',
    keywords: ['timestamp', 'unix time', 'date converter', 'epoch'],
    sampleInput: '1640000000000',
    sampleOutput: 'ISO: 2021-12-20T...',
    seoH1: 'Timestamp Converter — Unix to Date Online Free',
    seoExtra: {
      comparisonTitle: 'Timestamp vs Date',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Debug timestamps', 'API date fields', 'Log analysis'],
      longDescription: 'Convert Unix timestamps (seconds or milliseconds) to ISO and local dates, or paste a date to get the timestamp.',
    },
    faq: [
      { q: 'What format is the timestamp?', a: 'Numbers are treated as milliseconds if &gt; 10^12, otherwise seconds. Leave empty for current time.' },
    ],
    relatedTools: ['regex-tester', 'color-converter'],
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    route: '/regex-tester',
    category: 'utility',
    description: 'Test regular expressions. First line: regex pattern. Remaining lines: text to test. Shows all matches.',
    shortDescription: 'Test regex against text',
    icon: '.*',
    keywords: ['regex', 'regular expression', 'tester', 'pattern match'],
    sampleInput: '/\\w+/g\nHello world 123',
    sampleOutput: 'Match: "Hello" at index 0...',
    seoH1: 'Regex Tester — Test Regular Expressions Online Free',
    seoExtra: {
      comparisonTitle: 'Regex Tester',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Validate patterns', 'Extract matches', 'Learn regex'],
      longDescription: 'Paste a regex on the first line and sample text below. See all matches and groups. Client-side only.',
    },
    faq: [
      { q: 'How do I use it?', a: 'First line: your regex (e.g. \\d+ or /pattern/g). Next lines: text to search.' },
    ],
    relatedTools: ['timestamp-converter', 'text-case-converter'],
  },
  {
    id: 'jwt-generator',
    name: 'JWT Generator',
    route: '/jwt-generator',
    category: 'utility',
    description: 'Create a JWT from a JSON payload. Paste a JSON object; output is header.payload (unsigned; add signature in your app).',
    shortDescription: 'Build JWT from JSON payload',
    icon: 'JWT',
    keywords: ['jwt', 'json web token', 'generator', 'payload'],
    sampleInput: '{"sub":"user123","exp":9999999999}',
    sampleOutput: 'eyJhbGc... (unsigned)',
    seoH1: 'JWT Generator — Create JWT from JSON Online Free',
    seoExtra: {
      comparisonTitle: 'JWT Structure',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Testing JWTs', 'Learning JWT format', 'Payload encoding'],
      longDescription: 'Encode a JSON payload as JWT header and payload (base64url). Signing must be done in your application.',
    },
    faq: [
      { q: 'Is the JWT signed?', a: 'No. This tool outputs header.payload; you add the signature with your secret in your app.' },
      { q: 'What is the payload?', a: 'Any valid JSON object (e.g. sub, exp, custom claims).' },
    ],
    relatedTools: ['jwt-decoder', 'uuid-generator'],
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    route: '/hash-generator',
    category: 'utility',
    description: 'Generate MD5 and SHA-256 hashes of your input. Paste text; get hex hashes. 100% client-side.',
    shortDescription: 'MD5 and SHA-256 hash generator',
    icon: '#',
    keywords: ['hash', 'md5', 'sha256', 'checksum', 'generator'],
    sampleInput: 'hello',
    sampleOutput: 'MD5: 5d414...\nSHA-256: 2cf24d...',
    seoH1: 'Hash Generator — MD5 & SHA-256 Online Free',
    seoExtra: {
      comparisonTitle: 'MD5 vs SHA-256',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Checksums', 'Password hashing prep', 'Data integrity'],
      longDescription: 'Compute MD5 and SHA-256 hashes of any text. All hashing runs in your browser.',
    },
    faq: [
      { q: 'What algorithms are supported?', a: 'MD5 and SHA-256. Both are computed client-side.' },
      { q: 'Is this secure?', a: 'Hashing runs in your browser; data is not sent to any server.' },
    ],
    relatedTools: ['base64-encode', 'jwt-decoder'],
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    route: '/color-converter',
    category: 'utility',
    description: 'Convert between Hex, RGB, and HSL. Paste a color as #RRGGBB, rgb(r,g,b), or hsl(h,s%,l%).',
    shortDescription: 'Convert Hex, RGB, HSL colors',
    icon: '🎨',
    keywords: ['color converter', 'hex to rgb', 'rgb to hex', 'hsl'],
    sampleInput: '#2563eb',
    sampleOutput: 'Hex: #2563eb\nRGB: rgb(37, 99, 235)\nHSL: hsl(217, 84%, 53%)',
    seoH1: 'Color Converter — Hex, RGB, HSL Online Free',
    seoExtra: {
      comparisonTitle: 'Color Formats',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['CSS colors', 'Design handoff', 'Accessibility'],
      longDescription: 'Convert between hex, RGB, and HSL. Paste any supported format to see the others.',
    },
    faq: [
      { q: 'What formats are supported?', a: 'Hex (#RRGGBB), rgb(r,g,b), and hsl(h,s%,l%).' },
    ],
    relatedTools: ['timestamp-converter', 'text-case-converter'],
  },
  {
    id: 'text-case-converter',
    name: 'Text Case Converter',
    route: '/text-case-converter',
    category: 'utility',
    description: 'Convert text to lowercase, UPPERCASE, Title Case, camelCase, snake_case, kebab-case.',
    shortDescription: 'Convert text to different cases',
    icon: 'Aa',
    keywords: ['text case', 'camelCase', 'snake_case', 'kebab-case', 'converter'],
    sampleInput: 'hello world example',
    sampleOutput: 'lowercase: hello world example\nUPPERCASE: HELLO WORLD EXAMPLE\n...',
    seoH1: 'Text Case Converter — camelCase, snake_case Online Free',
    seoExtra: {
      comparisonTitle: 'Text Cases',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Variable names', 'CSS classes', 'API keys'],
      longDescription: 'Convert text to multiple case styles in one go. Client-side only.',
    },
    faq: [
      { q: 'What cases are supported?', a: 'lowercase, UPPERCASE, Title Case, camelCase, snake_case, kebab-case.' },
    ],
    relatedTools: ['regex-tester', 'color-converter'],
  },
];

export const TOOL_MAP = Object.fromEntries(TOOLS.map((t) => [t.id, t]));

export const CATEGORIES = [
  { id: 'json', label: 'JSON Tools' },
  { id: 'yaml', label: 'YAML Tools' },
  { id: 'xml', label: 'XML Tools' },
  { id: 'markup', label: 'Markup' },
  { id: 'security', label: 'Security' },
  { id: 'encoding', label: 'Encoding' },
  { id: 'utility', label: 'Utility Tools' },
] as const;
